// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: api_key_domains.sql

package store

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const addAPIKeyDomain = `-- name: AddAPIKeyDomain :exec
INSERT INTO api_key_domains (api_key_id, domain_id)
VALUES ($1, $2)
ON CONFLICT DO NOTHING
`

type AddAPIKeyDomainParams struct {
	ApiKeyID pgtype.UUID `json:"api_key_id"`
	DomainID pgtype.UUID `json:"domain_id"`
}

func (q *Queries) AddAPIKeyDomain(ctx context.Context, arg AddAPIKeyDomainParams) error {
	_, err := q.db.Exec(ctx, addAPIKeyDomain, arg.ApiKeyID, arg.DomainID)
	return err
}

const countAPIKeyDomains = `-- name: CountAPIKeyDomains :one
SELECT count(*)::bigint
FROM api_key_domains
WHERE api_key_id = $1
`

func (q *Queries) CountAPIKeyDomains(ctx context.Context, apiKeyID pgtype.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countAPIKeyDomains, apiKeyID)
	var column_1 int64
	err := row.Scan(&column_1)
	return column_1, err
}

const listAPIKeyDomains = `-- name: ListAPIKeyDomains :many
SELECT domain_id
FROM api_key_domains
WHERE api_key_id = $1
`

func (q *Queries) ListAPIKeyDomains(ctx context.Context, apiKeyID pgtype.UUID) ([]pgtype.UUID, error) {
	rows, err := q.db.Query(ctx, listAPIKeyDomains, apiKeyID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []pgtype.UUID
	for rows.Next() {
		var domain_id pgtype.UUID
		if err := rows.Scan(&domain_id); err != nil {
			return nil, err
		}
		items = append(items, domain_id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const replaceAPIKeyDomains = `-- name: ReplaceAPIKeyDomains :exec
DELETE FROM api_key_domains
WHERE api_key_id = $1
`

func (q *Queries) ReplaceAPIKeyDomains(ctx context.Context, apiKeyID pgtype.UUID) error {
	_, err := q.db.Exec(ctx, replaceAPIKeyDomains, apiKeyID)
	return err
}
