// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: cleanup.sql

package store

import (
	"context"
)

const cleanupExpiredLinks = `-- name: CleanupExpiredLinks :exec
DELETE FROM links l
USING users u
WHERE l.user_id = u.id
  AND u.keep_expired_links = false
  AND l.deleted_at IS NULL
  AND l.expires_at IS NOT NULL
  AND l.expires_at <= now()
`

func (q *Queries) CleanupExpiredLinks(ctx context.Context) error {
	_, err := q.db.Exec(ctx, cleanupExpiredLinks)
	return err
}
