// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: clicks.sql

package store

import (
	"context"
	"net/netip"

	"github.com/jackc/pgx/v5/pgtype"
)

const clickTotalsByDay = `-- name: ClickTotalsByDay :many
SELECT
  (date_trunc('day', clicked_at))::timestamptz AS day,
  count(*)::bigint AS clicks
FROM click_events
WHERE link_id = $1
  AND clicked_at >= $2
  AND clicked_at < $3
GROUP BY 1
ORDER BY 1 ASC
`

type ClickTotalsByDayParams struct {
	LinkID      pgtype.UUID        `json:"link_id"`
	ClickedAt   pgtype.Timestamptz `json:"clicked_at"`
	ClickedAt_2 pgtype.Timestamptz `json:"clicked_at_2"`
}

type ClickTotalsByDayRow struct {
	Day    pgtype.Timestamptz `json:"day"`
	Clicks int64              `json:"clicks"`
}

func (q *Queries) ClickTotalsByDay(ctx context.Context, arg ClickTotalsByDayParams) ([]ClickTotalsByDayRow, error) {
	rows, err := q.db.Query(ctx, clickTotalsByDay, arg.LinkID, arg.ClickedAt, arg.ClickedAt_2)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ClickTotalsByDayRow
	for rows.Next() {
		var i ClickTotalsByDayRow
		if err := rows.Scan(&i.Day, &i.Clicks); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const insertClickEvent = `-- name: InsertClickEvent :one
INSERT INTO click_events (link_id, clicked_at, referrer, user_agent, ip, country, device)
VALUES ($1, now(), $2, $3, $4, $5, $6)
RETURNING id, link_id, clicked_at, referrer, user_agent, ip, country, device
`

type InsertClickEventParams struct {
	LinkID    pgtype.UUID `json:"link_id"`
	Referrer  pgtype.Text `json:"referrer"`
	UserAgent pgtype.Text `json:"user_agent"`
	Ip        *netip.Addr `json:"ip"`
	Country   pgtype.Text `json:"country"`
	Device    pgtype.Text `json:"device"`
}

func (q *Queries) InsertClickEvent(ctx context.Context, arg InsertClickEventParams) (ClickEvent, error) {
	row := q.db.QueryRow(ctx, insertClickEvent,
		arg.LinkID,
		arg.Referrer,
		arg.UserAgent,
		arg.Ip,
		arg.Country,
		arg.Device,
	)
	var i ClickEvent
	err := row.Scan(
		&i.ID,
		&i.LinkID,
		&i.ClickedAt,
		&i.Referrer,
		&i.UserAgent,
		&i.Ip,
		&i.Country,
		&i.Device,
	)
	return i, err
}

const listClickEventsForLink = `-- name: ListClickEventsForLink :many
SELECT id, link_id, clicked_at, referrer, user_agent, ip, country, device
FROM click_events
WHERE link_id = $1
ORDER BY clicked_at DESC
LIMIT $2 OFFSET $3
`

type ListClickEventsForLinkParams struct {
	LinkID pgtype.UUID `json:"link_id"`
	Limit  int32       `json:"limit"`
	Offset int32       `json:"offset"`
}

func (q *Queries) ListClickEventsForLink(ctx context.Context, arg ListClickEventsForLinkParams) ([]ClickEvent, error) {
	rows, err := q.db.Query(ctx, listClickEventsForLink, arg.LinkID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ClickEvent
	for rows.Next() {
		var i ClickEvent
		if err := rows.Scan(
			&i.ID,
			&i.LinkID,
			&i.ClickedAt,
			&i.Referrer,
			&i.UserAgent,
			&i.Ip,
			&i.Country,
			&i.Device,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
