// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: domains.sql

package store

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createDomain = `-- name: CreateDomain :one
INSERT INTO domains (user_id, hostname, dns_token)
VALUES ($1, $2, $3)
RETURNING id, user_id, hostname, is_primary, status, dns_token, created_at, verified_at, default_tags
`

type CreateDomainParams struct {
	UserID   pgtype.UUID `json:"user_id"`
	Hostname string      `json:"hostname"`
	DnsToken string      `json:"dns_token"`
}

func (q *Queries) CreateDomain(ctx context.Context, arg CreateDomainParams) (Domain, error) {
	row := q.db.QueryRow(ctx, createDomain, arg.UserID, arg.Hostname, arg.DnsToken)
	var i Domain
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Hostname,
		&i.IsPrimary,
		&i.Status,
		&i.DnsToken,
		&i.CreatedAt,
		&i.VerifiedAt,
		&i.DefaultTags,
	)
	return i, err
}

const deleteDomain = `-- name: DeleteDomain :exec
DELETE FROM domains
WHERE id = $1 AND user_id = $2
`

type DeleteDomainParams struct {
	ID     pgtype.UUID `json:"id"`
	UserID pgtype.UUID `json:"user_id"`
}

func (q *Queries) DeleteDomain(ctx context.Context, arg DeleteDomainParams) error {
	_, err := q.db.Exec(ctx, deleteDomain, arg.ID, arg.UserID)
	return err
}

const getDomainByHostname = `-- name: GetDomainByHostname :one
SELECT id, user_id, hostname, is_primary, status, dns_token, created_at, verified_at, default_tags
FROM domains
WHERE user_id = $1 AND hostname = $2
`

type GetDomainByHostnameParams struct {
	UserID   pgtype.UUID `json:"user_id"`
	Hostname string      `json:"hostname"`
}

func (q *Queries) GetDomainByHostname(ctx context.Context, arg GetDomainByHostnameParams) (Domain, error) {
	row := q.db.QueryRow(ctx, getDomainByHostname, arg.UserID, arg.Hostname)
	var i Domain
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Hostname,
		&i.IsPrimary,
		&i.Status,
		&i.DnsToken,
		&i.CreatedAt,
		&i.VerifiedAt,
		&i.DefaultTags,
	)
	return i, err
}

const getDomainByID = `-- name: GetDomainByID :one
SELECT id, user_id, hostname, is_primary, status, dns_token, created_at, verified_at, default_tags
FROM domains
WHERE id = $1 AND user_id = $2
`

type GetDomainByIDParams struct {
	ID     pgtype.UUID `json:"id"`
	UserID pgtype.UUID `json:"user_id"`
}

func (q *Queries) GetDomainByID(ctx context.Context, arg GetDomainByIDParams) (Domain, error) {
	row := q.db.QueryRow(ctx, getDomainByID, arg.ID, arg.UserID)
	var i Domain
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Hostname,
		&i.IsPrimary,
		&i.Status,
		&i.DnsToken,
		&i.CreatedAt,
		&i.VerifiedAt,
		&i.DefaultTags,
	)
	return i, err
}

const getPrimaryDomain = `-- name: GetPrimaryDomain :one
SELECT id, user_id, hostname, is_primary, status, dns_token, created_at, verified_at, default_tags
FROM domains
WHERE user_id = $1 AND is_primary = true
`

func (q *Queries) GetPrimaryDomain(ctx context.Context, userID pgtype.UUID) (Domain, error) {
	row := q.db.QueryRow(ctx, getPrimaryDomain, userID)
	var i Domain
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Hostname,
		&i.IsPrimary,
		&i.Status,
		&i.DnsToken,
		&i.CreatedAt,
		&i.VerifiedAt,
		&i.DefaultTags,
	)
	return i, err
}

const getVerifiedDomainByID = `-- name: GetVerifiedDomainByID :one
SELECT id, user_id, hostname, is_primary, status, dns_token, created_at, verified_at, default_tags
FROM domains
WHERE id = $1 AND user_id = $2 AND status = 'verified'
`

type GetVerifiedDomainByIDParams struct {
	ID     pgtype.UUID `json:"id"`
	UserID pgtype.UUID `json:"user_id"`
}

func (q *Queries) GetVerifiedDomainByID(ctx context.Context, arg GetVerifiedDomainByIDParams) (Domain, error) {
	row := q.db.QueryRow(ctx, getVerifiedDomainByID, arg.ID, arg.UserID)
	var i Domain
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Hostname,
		&i.IsPrimary,
		&i.Status,
		&i.DnsToken,
		&i.CreatedAt,
		&i.VerifiedAt,
		&i.DefaultTags,
	)
	return i, err
}

const listDomains = `-- name: ListDomains :many
SELECT id, user_id, hostname, is_primary, status, dns_token, created_at, verified_at, default_tags
FROM domains
WHERE user_id = $1
ORDER BY is_primary DESC, created_at DESC
LIMIT $2 OFFSET $3
`

type ListDomainsParams struct {
	UserID pgtype.UUID `json:"user_id"`
	Limit  int32       `json:"limit"`
	Offset int32       `json:"offset"`
}

func (q *Queries) ListDomains(ctx context.Context, arg ListDomainsParams) ([]Domain, error) {
	rows, err := q.db.Query(ctx, listDomains, arg.UserID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Domain
	for rows.Next() {
		var i Domain
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Hostname,
			&i.IsPrimary,
			&i.Status,
			&i.DnsToken,
			&i.CreatedAt,
			&i.VerifiedAt,
			&i.DefaultTags,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markDomainVerified = `-- name: MarkDomainVerified :one
UPDATE domains
SET status = 'verified',
    verified_at = now()
WHERE id = $1 AND user_id = $2
RETURNING id, user_id, hostname, is_primary, status, dns_token, created_at, verified_at, default_tags
`

type MarkDomainVerifiedParams struct {
	ID     pgtype.UUID `json:"id"`
	UserID pgtype.UUID `json:"user_id"`
}

func (q *Queries) MarkDomainVerified(ctx context.Context, arg MarkDomainVerifiedParams) (Domain, error) {
	row := q.db.QueryRow(ctx, markDomainVerified, arg.ID, arg.UserID)
	var i Domain
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Hostname,
		&i.IsPrimary,
		&i.Status,
		&i.DnsToken,
		&i.CreatedAt,
		&i.VerifiedAt,
		&i.DefaultTags,
	)
	return i, err
}

const setPrimaryDomain = `-- name: SetPrimaryDomain :exec
UPDATE domains
SET is_primary = (id = $2)
WHERE user_id = $1
`

type SetPrimaryDomainParams struct {
	UserID pgtype.UUID `json:"user_id"`
	ID     pgtype.UUID `json:"id"`
}

func (q *Queries) SetPrimaryDomain(ctx context.Context, arg SetPrimaryDomainParams) error {
	_, err := q.db.Exec(ctx, setPrimaryDomain, arg.UserID, arg.ID)
	return err
}

const updateDomainDefaultTags = `-- name: UpdateDomainDefaultTags :one
UPDATE domains
SET default_tags = $3
WHERE id = $1 AND user_id = $2
RETURNING id, user_id, hostname, is_primary, status, dns_token, created_at, verified_at, default_tags
`

type UpdateDomainDefaultTagsParams struct {
	ID          pgtype.UUID `json:"id"`
	UserID      pgtype.UUID `json:"user_id"`
	DefaultTags []string    `json:"default_tags"`
}

func (q *Queries) UpdateDomainDefaultTags(ctx context.Context, arg UpdateDomainDefaultTagsParams) (Domain, error) {
	row := q.db.QueryRow(ctx, updateDomainDefaultTags, arg.ID, arg.UserID, arg.DefaultTags)
	var i Domain
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Hostname,
		&i.IsPrimary,
		&i.Status,
		&i.DnsToken,
		&i.CreatedAt,
		&i.VerifiedAt,
		&i.DefaultTags,
	)
	return i, err
}
