// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: home.sql

package store

import (
	"context"
	"net/netip"

	"github.com/jackc/pgx/v5/pgtype"
)

const listRecentClicks = `-- name: ListRecentClicks :many
SELECT
  ce.id,
  ce.clicked_at,
  ce.referrer,
  ce.user_agent,
  ce.ip,
  ce.country,
  ce.device,
  l.id AS link_id,
  l.alias,
  l.domain_id
FROM click_events ce
JOIN links l ON l.id = ce.link_id
WHERE l.user_id = $1
  AND l.deleted_at IS NULL
ORDER BY ce.clicked_at DESC
LIMIT $2
`

type ListRecentClicksParams struct {
	UserID pgtype.UUID `json:"user_id"`
	Limit  int32       `json:"limit"`
}

type ListRecentClicksRow struct {
	ID        int64              `json:"id"`
	ClickedAt pgtype.Timestamptz `json:"clicked_at"`
	Referrer  pgtype.Text        `json:"referrer"`
	UserAgent pgtype.Text        `json:"user_agent"`
	Ip        *netip.Addr        `json:"ip"`
	Country   pgtype.Text        `json:"country"`
	Device    pgtype.Text        `json:"device"`
	LinkID    pgtype.UUID        `json:"link_id"`
	Alias     string             `json:"alias"`
	DomainID  pgtype.UUID        `json:"domain_id"`
}

func (q *Queries) ListRecentClicks(ctx context.Context, arg ListRecentClicksParams) ([]ListRecentClicksRow, error) {
	rows, err := q.db.Query(ctx, listRecentClicks, arg.UserID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListRecentClicksRow
	for rows.Next() {
		var i ListRecentClicksRow
		if err := rows.Scan(
			&i.ID,
			&i.ClickedAt,
			&i.Referrer,
			&i.UserAgent,
			&i.Ip,
			&i.Country,
			&i.Device,
			&i.LinkID,
			&i.Alias,
			&i.DomainID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTopLinksByClicks = `-- name: ListTopLinksByClicks :many
SELECT
  l.id, l.user_id, l.domain_id, l.alias, l.target_url, l.title, l.tags, l.created_at, l.updated_at, l.expires_at, l.deleted_at,
  COALESCE(count(ce.id), 0)::bigint AS clicks
FROM links l
LEFT JOIN click_events ce
  ON ce.link_id = l.id
 AND ce.clicked_at >= now() - ($3::int * interval '1 day')
WHERE l.user_id = $1
  AND l.deleted_at IS NULL
GROUP BY l.id
ORDER BY clicks DESC, l.created_at DESC
LIMIT $2
`

type ListTopLinksByClicksParams struct {
	UserID  pgtype.UUID `json:"user_id"`
	Limit   int32       `json:"limit"`
	Column3 int32       `json:"column_3"`
}

type ListTopLinksByClicksRow struct {
	ID        pgtype.UUID        `json:"id"`
	UserID    pgtype.UUID        `json:"user_id"`
	DomainID  pgtype.UUID        `json:"domain_id"`
	Alias     string             `json:"alias"`
	TargetUrl string             `json:"target_url"`
	Title     pgtype.Text        `json:"title"`
	Tags      []string           `json:"tags"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
	ExpiresAt pgtype.Timestamptz `json:"expires_at"`
	DeletedAt pgtype.Timestamptz `json:"deleted_at"`
	Clicks    int64              `json:"clicks"`
}

func (q *Queries) ListTopLinksByClicks(ctx context.Context, arg ListTopLinksByClicksParams) ([]ListTopLinksByClicksRow, error) {
	rows, err := q.db.Query(ctx, listTopLinksByClicks, arg.UserID, arg.Limit, arg.Column3)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListTopLinksByClicksRow
	for rows.Next() {
		var i ListTopLinksByClicksRow
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.DomainID,
			&i.Alias,
			&i.TargetUrl,
			&i.Title,
			&i.Tags,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.ExpiresAt,
			&i.DeletedAt,
			&i.Clicks,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
