// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: links.sql

package store

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createLink = `-- name: CreateLink :one
INSERT INTO links (user_id, domain_id, alias, target_url, title, tags, expires_at)
VALUES ($1, $2, $3, $4, $5, $6, $7)
RETURNING id, user_id, domain_id, alias, target_url, title, tags, created_at, updated_at, expires_at, deleted_at
`

type CreateLinkParams struct {
	UserID    pgtype.UUID        `json:"user_id"`
	DomainID  pgtype.UUID        `json:"domain_id"`
	Alias     string             `json:"alias"`
	TargetUrl string             `json:"target_url"`
	Title     pgtype.Text        `json:"title"`
	Tags      []string           `json:"tags"`
	ExpiresAt pgtype.Timestamptz `json:"expires_at"`
}

func (q *Queries) CreateLink(ctx context.Context, arg CreateLinkParams) (Link, error) {
	row := q.db.QueryRow(ctx, createLink,
		arg.UserID,
		arg.DomainID,
		arg.Alias,
		arg.TargetUrl,
		arg.Title,
		arg.Tags,
		arg.ExpiresAt,
	)
	var i Link
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.DomainID,
		&i.Alias,
		&i.TargetUrl,
		&i.Title,
		&i.Tags,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ExpiresAt,
		&i.DeletedAt,
	)
	return i, err
}

const getActiveLinkByAlias = `-- name: GetActiveLinkByAlias :one
SELECT id, user_id, domain_id, alias, target_url, title, tags, created_at, updated_at, expires_at, deleted_at
FROM links
WHERE alias = $1
  AND deleted_at IS NULL
  AND (expires_at IS NULL OR expires_at > now())
`

func (q *Queries) GetActiveLinkByAlias(ctx context.Context, alias string) (Link, error) {
	row := q.db.QueryRow(ctx, getActiveLinkByAlias, alias)
	var i Link
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.DomainID,
		&i.Alias,
		&i.TargetUrl,
		&i.Title,
		&i.Tags,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ExpiresAt,
		&i.DeletedAt,
	)
	return i, err
}

const getLinkByID = `-- name: GetLinkByID :one
SELECT id, user_id, domain_id, alias, target_url, title, tags, created_at, updated_at, expires_at, deleted_at
FROM links
WHERE id = $1 AND user_id = $2
`

type GetLinkByIDParams struct {
	ID     pgtype.UUID `json:"id"`
	UserID pgtype.UUID `json:"user_id"`
}

func (q *Queries) GetLinkByID(ctx context.Context, arg GetLinkByIDParams) (Link, error) {
	row := q.db.QueryRow(ctx, getLinkByID, arg.ID, arg.UserID)
	var i Link
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.DomainID,
		&i.Alias,
		&i.TargetUrl,
		&i.Title,
		&i.Tags,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ExpiresAt,
		&i.DeletedAt,
	)
	return i, err
}

const listLinks = `-- name: ListLinks :many
SELECT id, user_id, domain_id, alias, target_url, title, tags, created_at, updated_at, expires_at, deleted_at
FROM links
WHERE user_id = $1
  AND (deleted_at IS NULL OR $3::boolean = true)
  AND ($5::text = '' OR $5::text = ANY(tags))
ORDER BY created_at DESC
LIMIT $2 OFFSET $4
`

type ListLinksParams struct {
	UserID  pgtype.UUID `json:"user_id"`
	Limit   int32       `json:"limit"`
	Column3 bool        `json:"column_3"`
	Offset  int32       `json:"offset"`
	Column5 string      `json:"column_5"`
}

func (q *Queries) ListLinks(ctx context.Context, arg ListLinksParams) ([]Link, error) {
	rows, err := q.db.Query(ctx, listLinks,
		arg.UserID,
		arg.Limit,
		arg.Column3,
		arg.Offset,
		arg.Column5,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Link
	for rows.Next() {
		var i Link
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.DomainID,
			&i.Alias,
			&i.TargetUrl,
			&i.Title,
			&i.Tags,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.ExpiresAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const softDeleteLink = `-- name: SoftDeleteLink :one
UPDATE links
SET deleted_at = now(),
    updated_at = now()
WHERE id = $1 AND user_id = $2 AND deleted_at IS NULL
RETURNING id, user_id, domain_id, alias, target_url, title, tags, created_at, updated_at, expires_at, deleted_at
`

type SoftDeleteLinkParams struct {
	ID     pgtype.UUID `json:"id"`
	UserID pgtype.UUID `json:"user_id"`
}

func (q *Queries) SoftDeleteLink(ctx context.Context, arg SoftDeleteLinkParams) (Link, error) {
	row := q.db.QueryRow(ctx, softDeleteLink, arg.ID, arg.UserID)
	var i Link
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.DomainID,
		&i.Alias,
		&i.TargetUrl,
		&i.Title,
		&i.Tags,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ExpiresAt,
		&i.DeletedAt,
	)
	return i, err
}

const updateLink = `-- name: UpdateLink :one
UPDATE links
SET domain_id = $3,
    alias = $4,
    target_url = $5,
    title = $6,
    tags = $7,
    expires_at = $8,
    updated_at = now()
WHERE id = $1 AND user_id = $2
RETURNING id, user_id, domain_id, alias, target_url, title, tags, created_at, updated_at, expires_at, deleted_at
`

type UpdateLinkParams struct {
	ID        pgtype.UUID        `json:"id"`
	UserID    pgtype.UUID        `json:"user_id"`
	DomainID  pgtype.UUID        `json:"domain_id"`
	Alias     string             `json:"alias"`
	TargetUrl string             `json:"target_url"`
	Title     pgtype.Text        `json:"title"`
	Tags      []string           `json:"tags"`
	ExpiresAt pgtype.Timestamptz `json:"expires_at"`
}

func (q *Queries) UpdateLink(ctx context.Context, arg UpdateLinkParams) (Link, error) {
	row := q.db.QueryRow(ctx, updateLink,
		arg.ID,
		arg.UserID,
		arg.DomainID,
		arg.Alias,
		arg.TargetUrl,
		arg.Title,
		arg.Tags,
		arg.ExpiresAt,
	)
	var i Link
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.DomainID,
		&i.Alias,
		&i.TargetUrl,
		&i.Title,
		&i.Tags,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ExpiresAt,
		&i.DeletedAt,
	)
	return i, err
}
