// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package store

import (
	"net/netip"

	"github.com/jackc/pgx/v5/pgtype"
)

type ApiKey struct {
	ID         pgtype.UUID        `json:"id"`
	UserID     pgtype.UUID        `json:"user_id"`
	KeyHash    string             `json:"key_hash"`
	Name       string             `json:"name"`
	CreatedAt  pgtype.Timestamptz `json:"created_at"`
	LastUsedAt pgtype.Timestamptz `json:"last_used_at"`
	RevokedAt  pgtype.Timestamptz `json:"revoked_at"`
}

type ApiKeyDomain struct {
	ApiKeyID pgtype.UUID `json:"api_key_id"`
	DomainID pgtype.UUID `json:"domain_id"`
}

type ClickEvent struct {
	ID        int64              `json:"id"`
	LinkID    pgtype.UUID        `json:"link_id"`
	ClickedAt pgtype.Timestamptz `json:"clicked_at"`
	Referrer  pgtype.Text        `json:"referrer"`
	UserAgent pgtype.Text        `json:"user_agent"`
	Ip        *netip.Addr        `json:"ip"`
	Country   pgtype.Text        `json:"country"`
	Device    pgtype.Text        `json:"device"`
}

type Domain struct {
	ID          pgtype.UUID        `json:"id"`
	UserID      pgtype.UUID        `json:"user_id"`
	Hostname    string             `json:"hostname"`
	IsPrimary   bool               `json:"is_primary"`
	Status      string             `json:"status"`
	DnsToken    string             `json:"dns_token"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	VerifiedAt  pgtype.Timestamptz `json:"verified_at"`
	DefaultTags []string           `json:"default_tags"`
}

type Link struct {
	ID        pgtype.UUID        `json:"id"`
	UserID    pgtype.UUID        `json:"user_id"`
	DomainID  pgtype.UUID        `json:"domain_id"`
	Alias     string             `json:"alias"`
	TargetUrl string             `json:"target_url"`
	Title     pgtype.Text        `json:"title"`
	Tags      []string           `json:"tags"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
	ExpiresAt pgtype.Timestamptz `json:"expires_at"`
	DeletedAt pgtype.Timestamptz `json:"deleted_at"`
}

type User struct {
	ID                   pgtype.UUID        `json:"id"`
	Email                string             `json:"email"`
	PasswordHash         string             `json:"password_hash"`
	CreatedAt            pgtype.Timestamptz `json:"created_at"`
	DisabledAt           pgtype.Timestamptz `json:"disabled_at"`
	RedirectDelaySeconds int32              `json:"redirect_delay_seconds"`
	KeepExpiredLinks     bool               `json:"keep_expired_links"`
	Timezone             string             `json:"timezone"`
}

type UserTag struct {
	ID        pgtype.UUID        `json:"id"`
	UserID    pgtype.UUID        `json:"user_id"`
	Name      string             `json:"name"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}
