// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: stats.sql

package store

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getUserStats = `-- name: GetUserStats :one
SELECT
  (SELECT count(*)::bigint FROM links l WHERE l.user_id = $1 AND l.deleted_at IS NULL) AS links_total,
  (SELECT count(*)::bigint
     FROM click_events ce
     JOIN links l ON l.id = ce.link_id
    WHERE l.user_id = $1 AND l.deleted_at IS NULL) AS clicks_total,
  (SELECT count(*)::bigint
     FROM click_events ce
     JOIN links l ON l.id = ce.link_id
    WHERE l.user_id = $1 AND l.deleted_at IS NULL AND ce.clicked_at >= now() - interval '24 hours') AS clicks_24h,
  (SELECT count(*)::bigint
     FROM click_events ce
     JOIN links l ON l.id = ce.link_id
    WHERE l.user_id = $1 AND l.deleted_at IS NULL AND ce.clicked_at >= now() - interval '7 days') AS clicks_7d
`

type GetUserStatsRow struct {
	LinksTotal  int64 `json:"links_total"`
	ClicksTotal int64 `json:"clicks_total"`
	Clicks24h   int64 `json:"clicks_24h"`
	Clicks7d    int64 `json:"clicks_7d"`
}

func (q *Queries) GetUserStats(ctx context.Context, userID pgtype.UUID) (GetUserStatsRow, error) {
	row := q.db.QueryRow(ctx, getUserStats, userID)
	var i GetUserStatsRow
	err := row.Scan(
		&i.LinksTotal,
		&i.ClicksTotal,
		&i.Clicks24h,
		&i.Clicks7d,
	)
	return i, err
}
