// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: tags.sql

package store

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createUserTag = `-- name: CreateUserTag :one
INSERT INTO user_tags (user_id, name)
VALUES ($1, $2)
RETURNING id, user_id, name, created_at
`

type CreateUserTagParams struct {
	UserID pgtype.UUID `json:"user_id"`
	Name   string      `json:"name"`
}

func (q *Queries) CreateUserTag(ctx context.Context, arg CreateUserTagParams) (UserTag, error) {
	row := q.db.QueryRow(ctx, createUserTag, arg.UserID, arg.Name)
	var i UserTag
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.CreatedAt,
	)
	return i, err
}

const deleteUserTag = `-- name: DeleteUserTag :exec
DELETE FROM user_tags
WHERE user_id = $1 AND name = $2
`

type DeleteUserTagParams struct {
	UserID pgtype.UUID `json:"user_id"`
	Name   string      `json:"name"`
}

func (q *Queries) DeleteUserTag(ctx context.Context, arg DeleteUserTagParams) error {
	_, err := q.db.Exec(ctx, deleteUserTag, arg.UserID, arg.Name)
	return err
}

const listUserTags = `-- name: ListUserTags :many
SELECT id, user_id, name, created_at
FROM user_tags
WHERE user_id = $1
ORDER BY name ASC
LIMIT $2 OFFSET $3
`

type ListUserTagsParams struct {
	UserID pgtype.UUID `json:"user_id"`
	Limit  int32       `json:"limit"`
	Offset int32       `json:"offset"`
}

func (q *Queries) ListUserTags(ctx context.Context, arg ListUserTagsParams) ([]UserTag, error) {
	rows, err := q.db.Query(ctx, listUserTags, arg.UserID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []UserTag
	for rows.Next() {
		var i UserTag
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Name,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const tagCountsFromLinks = `-- name: TagCountsFromLinks :many
SELECT
  t.tag::text AS name,
  count(*)::bigint AS link_count
FROM (
  SELECT unnest(tags) AS tag
  FROM links
  WHERE user_id = $1 AND deleted_at IS NULL
) t
GROUP BY 1
ORDER BY 2 DESC, 1 ASC
LIMIT $2 OFFSET $3
`

type TagCountsFromLinksParams struct {
	UserID pgtype.UUID `json:"user_id"`
	Limit  int32       `json:"limit"`
	Offset int32       `json:"offset"`
}

type TagCountsFromLinksRow struct {
	Name      string `json:"name"`
	LinkCount int64  `json:"link_count"`
}

func (q *Queries) TagCountsFromLinks(ctx context.Context, arg TagCountsFromLinksParams) ([]TagCountsFromLinksRow, error) {
	rows, err := q.db.Query(ctx, tagCountsFromLinks, arg.UserID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []TagCountsFromLinksRow
	for rows.Next() {
		var i TagCountsFromLinksRow
		if err := rows.Scan(&i.Name, &i.LinkCount); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
