// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: users.sql

package store

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createUser = `-- name: CreateUser :one
INSERT INTO users (email, password_hash)
VALUES ($1, $2)
RETURNING id, email, password_hash, created_at, disabled_at, redirect_delay_seconds, keep_expired_links, timezone
`

type CreateUserParams struct {
	Email        string `json:"email"`
	PasswordHash string `json:"password_hash"`
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (User, error) {
	row := q.db.QueryRow(ctx, createUser, arg.Email, arg.PasswordHash)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.PasswordHash,
		&i.CreatedAt,
		&i.DisabledAt,
		&i.RedirectDelaySeconds,
		&i.KeepExpiredLinks,
		&i.Timezone,
	)
	return i, err
}

const disableUser = `-- name: DisableUser :one
UPDATE users
SET disabled_at = now()
WHERE id = $1
RETURNING id, email, password_hash, created_at, disabled_at, redirect_delay_seconds, keep_expired_links, timezone
`

func (q *Queries) DisableUser(ctx context.Context, id pgtype.UUID) (User, error) {
	row := q.db.QueryRow(ctx, disableUser, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.PasswordHash,
		&i.CreatedAt,
		&i.DisabledAt,
		&i.RedirectDelaySeconds,
		&i.KeepExpiredLinks,
		&i.Timezone,
	)
	return i, err
}

const enableUser = `-- name: EnableUser :one
UPDATE users
SET disabled_at = NULL
WHERE id = $1
RETURNING id, email, password_hash, created_at, disabled_at, redirect_delay_seconds, keep_expired_links, timezone
`

func (q *Queries) EnableUser(ctx context.Context, id pgtype.UUID) (User, error) {
	row := q.db.QueryRow(ctx, enableUser, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.PasswordHash,
		&i.CreatedAt,
		&i.DisabledAt,
		&i.RedirectDelaySeconds,
		&i.KeepExpiredLinks,
		&i.Timezone,
	)
	return i, err
}

const getUserByEmail = `-- name: GetUserByEmail :one
SELECT id, email, password_hash, created_at, disabled_at, redirect_delay_seconds, keep_expired_links, timezone
FROM users
WHERE email = $1
`

func (q *Queries) GetUserByEmail(ctx context.Context, email string) (User, error) {
	row := q.db.QueryRow(ctx, getUserByEmail, email)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.PasswordHash,
		&i.CreatedAt,
		&i.DisabledAt,
		&i.RedirectDelaySeconds,
		&i.KeepExpiredLinks,
		&i.Timezone,
	)
	return i, err
}

const getUserByID = `-- name: GetUserByID :one
SELECT id, email, password_hash, created_at, disabled_at, redirect_delay_seconds, keep_expired_links, timezone
FROM users
WHERE id = $1
`

func (q *Queries) GetUserByID(ctx context.Context, id pgtype.UUID) (User, error) {
	row := q.db.QueryRow(ctx, getUserByID, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.PasswordHash,
		&i.CreatedAt,
		&i.DisabledAt,
		&i.RedirectDelaySeconds,
		&i.KeepExpiredLinks,
		&i.Timezone,
	)
	return i, err
}

const getUserSettings = `-- name: GetUserSettings :one
SELECT id, email, password_hash, created_at, disabled_at, redirect_delay_seconds, keep_expired_links, timezone
FROM users
WHERE id = $1
`

func (q *Queries) GetUserSettings(ctx context.Context, id pgtype.UUID) (User, error) {
	row := q.db.QueryRow(ctx, getUserSettings, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.PasswordHash,
		&i.CreatedAt,
		&i.DisabledAt,
		&i.RedirectDelaySeconds,
		&i.KeepExpiredLinks,
		&i.Timezone,
	)
	return i, err
}

const listUsers = `-- name: ListUsers :many
SELECT id, email, password_hash, created_at, disabled_at, redirect_delay_seconds, keep_expired_links, timezone
FROM users
ORDER BY created_at DESC
LIMIT $1 OFFSET $2
`

type ListUsersParams struct {
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

func (q *Queries) ListUsers(ctx context.Context, arg ListUsersParams) ([]User, error) {
	rows, err := q.db.Query(ctx, listUsers, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []User
	for rows.Next() {
		var i User
		if err := rows.Scan(
			&i.ID,
			&i.Email,
			&i.PasswordHash,
			&i.CreatedAt,
			&i.DisabledAt,
			&i.RedirectDelaySeconds,
			&i.KeepExpiredLinks,
			&i.Timezone,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateUserPassword = `-- name: UpdateUserPassword :one
UPDATE users
SET password_hash = $2
WHERE id = $1
RETURNING id, email, password_hash, created_at, disabled_at, redirect_delay_seconds, keep_expired_links, timezone
`

type UpdateUserPasswordParams struct {
	ID           pgtype.UUID `json:"id"`
	PasswordHash string      `json:"password_hash"`
}

func (q *Queries) UpdateUserPassword(ctx context.Context, arg UpdateUserPasswordParams) (User, error) {
	row := q.db.QueryRow(ctx, updateUserPassword, arg.ID, arg.PasswordHash)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.PasswordHash,
		&i.CreatedAt,
		&i.DisabledAt,
		&i.RedirectDelaySeconds,
		&i.KeepExpiredLinks,
		&i.Timezone,
	)
	return i, err
}

const updateUserSettings = `-- name: UpdateUserSettings :one
UPDATE users
SET redirect_delay_seconds = $2,
    keep_expired_links = $3,
    timezone = $4
WHERE id = $1
RETURNING id, email, password_hash, created_at, disabled_at, redirect_delay_seconds, keep_expired_links, timezone
`

type UpdateUserSettingsParams struct {
	ID                   pgtype.UUID `json:"id"`
	RedirectDelaySeconds int32       `json:"redirect_delay_seconds"`
	KeepExpiredLinks     bool        `json:"keep_expired_links"`
	Timezone             string      `json:"timezone"`
}

func (q *Queries) UpdateUserSettings(ctx context.Context, arg UpdateUserSettingsParams) (User, error) {
	row := q.db.QueryRow(ctx, updateUserSettings,
		arg.ID,
		arg.RedirectDelaySeconds,
		arg.KeepExpiredLinks,
		arg.Timezone,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.PasswordHash,
		&i.CreatedAt,
		&i.DisabledAt,
		&i.RedirectDelaySeconds,
		&i.KeepExpiredLinks,
		&i.Timezone,
	)
	return i, err
}
